version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq-development
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - local

networks:
  local:
    driver: bridge