api:
  message:
    center:
      url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      deviceClient:
        connectTimeout: 5000
        readTimeout: 5000