version: '3'

services:
  mq:
    image: rabbitmq:3.5.6-management
    container_name: "rabbitmq-poc-blockhound"
    expose:
      - "5672"
      - "15672"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  database:
    image: postgres:12.4-alpine
    container_name: "postgres-poc-blockhound"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=poc-blockhound_db
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-backend
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d

networks:
  network-backend:
    driver: bridge